#pragma once

#include <vector>
#include <random>
#include <numbers>
#include <stdexcept>
#include <tuple>
#include <unordered_map>
#include "potentials.cpp"
#include "proposal_inversion.cpp"


std::tuple<std::vector<double>, std::vector<double>> propagate_mcmc(double& s0,
                                                                    double stepSize, 
                                                                    double beta, 
                                                                    int replicaId,
                                                                    std::vector<std::vector<double>> vParams, 
                                                                    long nSteps, 
                                                                    std::default_random_engine& gen,
                                                                    std::function< std::vector<double> ( const std::vector<double>&, 
                                                                                                         const std::vector<std::vector<double>>& ) > potential,
                                                                    std::function< double ( std::vector<double>&, 
                                                                                            std::default_random_engine&) > proposal,
                                                                    std::vector<double> walls)
{
    /**
    *
    * @brief Generates a realization of the Markov chain using the Metropolis
    *        Monte Carlo algorithm. Returns results as a tuple of two vectors.
    *
    * @param  s0        - Starting polong.
    * @param  step_size - The size of the steps to be taken i.e. standard
    *                     deviation of the Gaussian distribution used to 
    *                     propose steps.
    * @param  vParams   - Parameters for the potential energy landscape.
    * @param  beta      - 1/kT for calculating Boltzmann weights.
    * @param  replicaId - The replica index of the potential parameters.
    * @param  nSteps    - The number of Monte Carlo steps to be taken.
    * @param  potential - Choice of potential function for the simulation.
    *                     Must be `gaussian`, `harmonic` or `quartic`.
    * @param  proposal  - Choice of proposal function for the simulation.
    *                     Must be `gaussian` or `uniform`.
    * @param  walls     - The walls from where the particle is reflected.
    *                     The limits of the parameter with respect to which
    *                     the free energy is projected.
    *
    * 
    * @result positions - Set of positions generated by the Monte Carlo 
    *                     steps.
    * @result energies  - Set of energies for the positions visited.
    * 
    */

    std::uniform_real_distribution<double> uni_dist(0.0, 1.0);
	
    // Initialize vectors for positions, energies, inverse-temperature 
    std::vector<double> positions{};
    std::vector<double> energies{};

    for(long i = 0; i < nSteps; ++i)
    {        
        std::vector<double> currStep{s0, stepSize};

        double s1{proposal(currStep, gen)};
        
        currStep[1] = s1;

        // Calculate energy
        std::vector<double> Es{potential(currStep, vParams)};
        /**
         * Still within bounds?
        */
        if ( ! ((s0 < walls[1] && s0 > walls[0]) && 
                (s1 < walls[1] && s1 > walls[0])) )
        {
            std::cout << '\n' << s0 << ", "<< s1 << std::endl;
            throw std::runtime_error("You crossed a line tough guy.");
        }        
        


        // if ( ! (s0 < walls[1] && s0 > walls[0]) )
        //     throw std::runtime_error("You crossed a line tough guy.");

        
        // if (!(s1 < walls[1] && s1 > walls[0]))
        //     throw std::runtime_error("You crossed a line tough guy.");
            

        // std::cout << "Step " << i << " (current, proposed): " << currStep[0] << ", " << currStep[1] << '\n';
        
        /**
         * Calculate Boltzmann weights for current and next states 
         * respectively.  
        */ 

	    std::vector<double> probs = BoltzmannWeight(std::vector<double>{Es[1] - Es[0]}, beta);
        double p_acc = std::min(1.0, probs[0]);
        

	    // Perform the Metropolis Monte Carlo step
        double rand_val = uni_dist(gen);	
        
        if(rand_val < p_acc)
            s0 = s1;
        
        // std::cout << "After step " << i << ": " << s0 << '\n';

        positions.push_back(s0);   
        energies.push_back(Es[0]);  
        
    }

    // Return tuple of positions and energies
    return std::make_tuple(positions, energies); 
}


bool accept_tremd_exchange(std::vector<double> Es, 
                           std::vector<double> betas,
                           std::default_random_engine& gen)
{
    /**
     * @brief   Implementation of the acceptance criterion for temperature
     *          replica exchange MCMC.
     * 
     * @param   Es    - Energy values
     * @param   betas - Inverse temperatures
     * @param   gen   - Random number generator for the acceptance condition
     */

    double p_acc = std::min(1.0, std::exp((betas[0] - betas[1]) * (Es[0] - Es[1])));

    // Pick a number from a uniform distribution in [0, 1]
    std::uniform_real_distribution<double> uni_dist(0.0f, 1.0f);

    // std::cout << betas[0] << ',' << betas[1] << ',' << p_acc << '\n';

    // Perform the Metropolis Monte Carlo step and return result
    return uni_dist(gen) < p_acc;
}



bool accept_hremd_exchange(std::vector<double> Es, 
                           std::vector<double> betas, 
                           std::default_random_engine& gen)
{
    /**
     * @brief   Implementation of the acceptance criterion for Hamiltonian
     *          replica exchange MCMC.
     * 
     * @param   Es    - Energy values
     * @param   betas - Inverse temperatures
     * @param   gen   - Random number generator for the acceptance condition
     */

    double p_acc = std::min(1.0, std::exp(-(betas[0] * ( Es[1] - Es[0] )) - (betas[1] * ( Es[3] - Es[2] )) ) );
    
    // Pick a number from a uniform distribution in [0, 1]
    std::uniform_real_distribution<double> uni_dist(0.0f, 1.0f);

    // Perform the Metropolis Monte Carlo step and return result
    return uni_dist(gen) < p_acc;
}




void run_trex(std::vector<ReplicaInfo>& init_reps,
                               double step_size, 
                               long n_steps, 
                               long n_ex, 
                               std::function< std::vector<double> ( const std::vector<double>&, 
                                                                    const std::vector<std::vector<double>>& ) > potential,
                               std::function< double ( std::vector<double>&, 
                                                       std::default_random_engine&) > proposal, 
                               char ex_type = 't')
{
    // Initialize random number generator
    std::random_device r;
    std::default_random_engine gen(r());
    std::vector<double> betas_;
    bool ex_jk = true;
    size_t k_{0}, k{0}, j{0};

    std::vector<double> Es;
    size_t nreps = init_reps.size();
    std::vector<size_t> indices(nreps);
        
    std::cout << "=== Starting MCMC TREx " << " ===" << std::endl;
    
    for(long i = 0; i < n_ex; ++i)
    {                
        // Propagate all replicas
        for(size_t j = 0; j < nreps; ++j)
        {
            ReplicaInfo& curr_rep = init_reps[j];
            
            auto [positions, energies] = propagate_mcmc(curr_rep.x0, 
                                                        step_size, 
                                                        curr_rep.betas.back(),
                                                        curr_rep.repids.back(),
                                                        curr_rep.vParams,  
                                                        n_steps, 
                                                        gen, 
                                                        potential, 
                                                        proposal, 
                                                        curr_rep.walls);

            double temp_beta{curr_rep.betas.back()};
            int temp_repid{curr_rep.repids.back()};
            // std::cout << temp_beta << ", " << temp_repid << '\n';
            for (size_t WriteIdx=0; WriteIdx < n_steps; ++WriteIdx)
            {
                curr_rep.positions.push_back(positions[WriteIdx]);
                curr_rep.freeEnergy.push_back(energies[WriteIdx]); 
            }    

            for (size_t WriteIdx=0; WriteIdx < n_steps - 1; ++WriteIdx)
            {
                curr_rep.repids.push_back(temp_repid);
                curr_rep.betas.push_back(temp_beta);
            }    
                
        }
        
        std::iota(indices.begin(), indices.end(), 0);
        std::sort(indices.begin(), indices.end(), 
                [&init_reps](size_t i, size_t j){
                    return init_reps[i].betas.back() < init_reps[j].betas.back();
                });
            
        // std::vector<size_t> reverse_map(nreps);

        // for (size_t idx=0; idx < nreps; ++idx)
        //     reverse_map[indices[idx]] = idx;

        for(size_t j_ = ((i % 2) == 0)?0:1; j_ < nreps; j_ += 2)
        {
            k_ = (j_ + 1) % nreps;

            j = indices[j_];
            k = indices[k_];

            betas_ = {init_reps[j].betas.back(), init_reps[k].betas.back()};
            switch(ex_type)
            {
                case 't':
                    Es = {init_reps[j].freeEnergy.back(), init_reps[k].freeEnergy.back()};
                    ex_jk = accept_tremd_exchange(Es, betas_, gen);
                    break;
                    
                case 'h':
                    Es = {
                        init_reps[j].freeEnergy.back(),
                        potential(std::vector<double>{init_reps[k].positions.back()}, init_reps[j].vParams)[0],
                        init_reps[k].freeEnergy.back(),
                        potential(std::vector<double>{init_reps[j].positions.back()}, init_reps[k].vParams)[0]
                    };
                    ex_jk = accept_hremd_exchange(Es, betas_, gen);
                    break;
                    
                default:
                    throw std::runtime_error("Invalid exchange method: '" + std::string(1, ex_type) + "'");
            }
            
            if (ex_jk)
            {
                // Exchange successful, switch params and append betas
                std::swap(init_reps[j].vParams, init_reps[k].vParams);
                
                double temp_beta1{init_reps[j].betas.back()}, temp_beta2{init_reps[k].betas.back()};
                init_reps[j].betas.push_back(temp_beta2);
                init_reps[k].betas.push_back(temp_beta1);
                
                int repj{init_reps[j].repids.back()}, repk{init_reps[k].repids.back()};
                init_reps[j].repids.push_back(repk);
                init_reps[k].repids.push_back(repj);
            }            
            else
            {
                // No exchange, keep same betas
                
                double temp_beta{init_reps[j].betas.back()};
                init_reps[j].betas.push_back(temp_beta);

                temp_beta =init_reps[k].betas.back();
                init_reps[k].betas.push_back(temp_beta);
                

                int repj{init_reps[j].repids.back()}, repk{init_reps[k].repids.back()};
                init_reps[j].repids.push_back(repj);
                init_reps[k].repids.push_back(repk);
            }
        }    
    }

}